config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" } 
  root "trivia#index"
  get "trivia/ranking/:score" => "trivia#ranking"
  resources :answer, only: [] do
    get :check_answer, :on => :member
  end
  resources :questions
  resources :suggestions, only: [:new, :create, :index]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :answer, presence: true
end

  

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers
  validates :question, presence: true 
  validate :one_answer_is_correct

  def random_answers
    answers.shuffle
  end

  def correct_answer
    answers.where("is_correct=true").first
  end

  def one_answer_is_correct
    unless answers.collect {|a| a.is_correct}.include?(true)
      errors.add(:answers, "At least one answer has to be correct")
    end    
  end
end

app/models/rank.rb
class Rank

  attr_reader :rank_name  

  RANKS = [
    "Gabor",
    "Borfas",
    "Smenar",
    "Peste",
    "Baiat",
    "Frate",
    "Veteran"
  ]

  def initialize(score, quiz_length)
    @score = score
    @quiz_length = quiz_length
  end

  def rank_name
    @rank_name ||= RANKS[closest_percentage]
  end

  private

  def percentage
    ((@score * 100) / @quiz_length).round(2)
  end

  def closest_percentage
    i = ((percentage.to_f * RANKS.count)/100).round
    i -= 1 if i == RANKS.count
    i 
  end
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  validates :suggestion, presence: true 
  validates :email, presence: true 
  validates_format_of :email,:with => Devise::email_regexp
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController  
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
  def check_answer
    @answer = Answer.find(params[:id])
    if @answer.is_correct
      render json: { correct_answer_id: @answer.id }, status: 200
    else
      render json: { correct_answer_id: @answer.question.correct_answer.id, wrong_answer_id: @answer.id }, status: 422
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < AdminController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    4.times { @question.answers.build}
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, answers_attributes: [:answer, :is_correct] )
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    flash[:notice] = 'Registrations are not open yet, but please check back soon'
    redirect_to root_path
  end

  def create
    flash[:notice] = 'Registrations are not open yet, but please check back soon'
    redirect_to root_path
  end

  def after_sign_up_path_for(resource)
    signed_in_root_path(resource)
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < AdminController
  before_action :authenticate_user!, only: :index

  def index
    @suggestions = Suggestion.paginate(:page => params[:page], :per_page => 12)
  end

  def new
    @suggestion = Suggestion.new
  end

  def create
    @suggestion = Suggestion.new(suggestion_params)
    respond_to do |format|
      if verify_recaptcha(:model => @suggestion, :message => "Eroare la reCAPTCHA! ESTI GABOR?") && @suggestion.save
        format.html { redirect_to root_path, notice: 'Am notat sugestia ta. Multumim' }
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.html { render :new }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def suggestion_params
    params.require(:suggestion).permit(:suggestion, :email)
  end
end

app/controllers/trivia_controller.rb
class TriviaController < ApplicationController
  def index
    random_ids = Question.pluck(:id).sort_by { rand }.slice(0, ENV['QUIZ_LENGTH'].to_i)
    @questions = Question.where(:id => random_ids)
  end

  def ranking
    @rank = Rank.new(params[:score].to_i, ENV['QUIZ_LENGTH'].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_for(controller_name)
    params[:controller] == controller_name ? 'active' : ''
  end
end

app/helpers/trivia_helper.rb
module TriviaHelper
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BugTrivia
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if notice
      %p.alert.alert-success 
        = notice
    - if alert
      %p.alert.alert-danger
        = alert    

    = render "shared/navigation"
    .container-fluid
      = yield
  = javascript_include_tag 'base', 'data-turbolinks-track' => true

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title B.U.G. Mafia - Trivia
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "shared/scripts"
    - if notice
      %p.alert.alert-success
        = notice
    - if alert
      %p.alert.alert-danger
        = alert
    = render "shared/navigation"
    = yield
    %footer{class: "footer"}
      .container-fluid.center
        = "Powered by A.E.B."
        %a{href: "https://github.com/cbordei/trivia", target: "blank"}
          = image_tag "github_logo.png", size: "30x30"
        %br
        = link_to "SUGEREAZA O INTREBARE", new_suggestion_path

    .hidden
      = image_tag "maxresdefault.jpg", id: "share_image_tag"
  = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/questions/_form.html.haml
.container-fluid
  = form_for(@question) do |f|
    - if @question.errors.any?
      - @question.errors.full_messages.each do |message|
        %p.alert.alert-danger= message      
    .form-group
      = f.label :question
      = f.text_field :question, id: "question", class: "form-control"
      = f.fields_for :answers do |answers_form|
        = answers_form.label :answer
        = answers_form.label :is_correct
        = answers_form.check_box :is_correct
        = answers_form.text_field :answer, id: "answer", class: "form-control"        
    %button.btn.btn-default{:type => "submit"} Submit

app/views/questions/edit.html.haml
%h1 Editing question
.pull-right
  = link_to 'Show', @question
  |
  = link_to 'Back', questions_path

= render 'form'

app/views/questions/index.html.haml
%h1 Listing questions  
.pull-right.btn.btn-default
  = link_to 'New Question', new_question_path
.table-responsive
  %table.table
    %thead
      %tr
        %th #
        %th Question
        %th 
        %th 
        %th 
    %tbody
      - @questions.each do |question|
        %tr
          %td= question.id
          %td= question.question
          %td= link_to 'Show', question
          %td= link_to 'Edit', edit_question_path(question)
          %td= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }

= will_paginate @questions

app/views/questions/new.html.haml
%h1 New question
.pull-right
  = link_to 'Back', questions_path
= render 'form'

app/views/questions/show.html.haml
%h1= @question.question
.pull-right
  = link_to 'Edit', edit_question_path(@question)
  |
  = link_to 'Back', questions_path
.container-fluid
  - @question.answers.each do |answer|
    .row
      = answer.answer

app/views/shared/_navigation.html.haml
- if user_signed_in?
  #simple-nav-pills
    %ul.nav.nav-pills
      %li{:role => "presentation", class: active_for("trivia")}
        = link_to "Quiz", root_path
      %li{:role => "presentation", class: active_for("questions")}
        = link_to "Questions", questions_path
      %li{:role => "presentation", class: active_for("suggestions")}
        = link_to "Suggestions", suggestions_path
      %p.navbar-text.navbar-right
        = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'

app/views/shared/_scripts.html.haml
:javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '#{ENV['FB_APP_ID']}',
      xfbml      : true,
      version    : 'v2.2'
    });
  };
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

app/views/suggestions/index.html.haml
%h1 Listing Suggestions  
.table-responsive
  %table.table
    %thead
      %tr
        %th #
        %th Question
        %th 
        %th 
        %th 
    %tbody
      - @suggestions.each do |suggestion|
        %tr
          %td= suggestion.id
          %td= suggestion.email
          %td= suggestion.suggestion

= will_paginate @suggestions

app/views/suggestions/new.html.haml
%h1
  = "B.U.G. Mafia Quiz"
.container-fluid  
  = form_for(@suggestion) do |f|
    - if @suggestion.errors.any?
      - @suggestion.errors.full_messages.each do |message|
        %p.alert.alert-danger= message      
    .form-group
      = f.label :email
      = f.text_field :email, id: "email", class: "form-control", placeholder: "actionar@sc-strazile.ro"
      = f.label :suggestion
      = f.text_area :suggestion, id: "suggestion", class: "form-control", placeholder: "Cat de lunga e povestea? Fara sfarsit etc"
      = "Test Anti-Gabor"
      = recaptcha_tags
    %button.btn.btn-default{:type => "submit"} Submit
    %br
    = link_to "Back", root_path

app/views/trivia/index.html.haml
:javascript
  var questions = #{(render partial: "trivia/questions", object: @questions , formats: [:json])};

#js-quiz-container